# Generated by Django 3.2.5 on 2021-07-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your Name ')),
                ('age', models.IntegerField(verbose_name='Your Age ')),
                ('dob', models.DateField(verbose_name='Date of Birth ')),
                ('mobile', models.CharField(max_length=15, verbose_name='Your Mobile ')),
                ('email', models.EmailField(max_length=75, verbose_name='Your Email ')),
                ('city', models.CharField(max_length=50, verbose_name='Your City ')),
                ('website', models.CharField(max_length=40, verbose_name='Your Website ')),
                ('degree', models.CharField(max_length=40, verbose_name='Your Qualification ')),
                ('profile', models.CharField(max_length=40, verbose_name='Your Profile ')),
                ('shor_desc', models.TextField(max_length=200, verbose_name='Your Short Description ')),
                ('desc', models.TextField(max_length=600, verbose_name='About You ')),
                ('pimg', models.ImageField(upload_to='about', verbose_name='Upload Image ')),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50, verbose_name='Degree ')),
                ('year', models.CharField(max_length=20, verbose_name='Duration of Degree ')),
                ('university', models.CharField(max_length=75, verbose_name='Univercity Name ')),
                ('desc', models.TextField(max_length=300, verbose_name='Education Description')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=50, verbose_name='Profile ')),
                ('year', models.CharField(max_length=20, verbose_name='Total Experience ')),
                ('company_name', models.CharField(max_length=75, verbose_name='Company Name ')),
                ('desc', models.TextField(max_length=300, verbose_name='Exprience Description ')),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Portfolio Title ')),
                ('desc', models.TextField(max_length=500, verbose_name='Portfolio Description ')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='Portfolio Image ')),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Portfolio Title ')),
                ('desc', models.TextField(max_length=500, verbose_name='Portfolio Description ')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=20, verbose_name='Add Your Skill ')),
                ('rate', models.IntegerField(verbose_name='Rate your self in % ')),
                ('desc', models.TextField(max_length=200, verbose_name='Skill description ')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
